/* AI Roast Generator
Developed using AI (Claude)
Code refined after debugging and improvements


 * ============================================================
 *  ROAST GENERATOR 3000 — v2.0 (Now With Devastating Closings)
 *  Written by: A Sleep-Deprived First Year CSE Student (CGPA: 10.0)
 *  Purpose: To roast your friends so hard they question their life choices
 * ============================================================
 *
 * CONCEPTS USED IN THIS PROGRAM (for fellow beginners):
 *  - #include      : Importing libraries (like copy-pasting superpowers)
 *  - string        : A data type for text
 *  - array         : A fixed-size list of items
 *  - rand() % n    : Random number between 0 and n-1
 *  - srand()       : Seeds the random number generator (makes it actually random)
 *  - time(0)       : Current time in seconds (used as a seed so roasts change every run)
 *  - cin / cout    : Console input / output
 *  - getline()     : Reads a full line including spaces
 */

#include <iostream>   // For cin and cout (input/output)
#include <string>     // For the string data type
#include <cstdlib>    // For rand() and srand() (random number functions)
#include <ctime>      // For time() — lets us seed random differently each run

using namespace std; // So we don't have to type "std::" before everything

int main() {

    // -------------------------------------------------------
    // STEP 1: Seed the random number generator
    // -------------------------------------------------------
    srand(time(0));

    // -------------------------------------------------------
    // STEP 2: Greet the user (before destroying them)
    // -------------------------------------------------------
    cout << "============================================" << endl;
    cout << "        WELCOME TO ROAST GENERATOR 3000     " << endl;
    cout << "    (Warning: Ego not included. Bring your own.)" << endl;
    cout << "============================================" << endl;
    cout << endl;

    // -------------------------------------------------------
    // STEP 3: Ask for the user's name
    // -------------------------------------------------------
    string name;
    cout << "Enter your name (so we know who to roast): ";
    getline(cin, name);
    cout << endl;

    // -------------------------------------------------------
    // STEP 4: Store 10 roast templates in a string array
    // -------------------------------------------------------
    const int NUM_ROASTS = 10;

    string roasts[NUM_ROASTS] = {
        "NAME, your Wi-Fi password is more complex than your personality.",
        "NAME, even your Google search history feels sorry for you.",
        "NAME, I've seen better decision-making from a coin toss.",
        "NAME, your brain called — it said it's taking an indefinite sabbatical.",
        "NAME, scientists studied you and concluded evolution sometimes goes in reverse.",
        "NAME, your grades and your social life are in a competition to see who can disappear first.",
        "NAME, I'd explain the joke but I don't want you hurting yourself thinking.",
        "NAME, even the compiler has more optimism about your future than your parents do.",
        "NAME, your self-awareness is still loading... Please wait.",
        "NAME, I asked ChatGPT to rate your personality. It said 'Insufficient data. Too boring to analyze.'"
    };

    // -------------------------------------------------------
    // STEP 5: Store 10 closing statement templates
    // -------------------------------------------------------
    const int NUM_CLOSINGS = 10;

    string closings[NUM_CLOSINGS] = {
        "Don't cry, NAME. Tears won't fix your personality.",
        "This was generated by a computer, NAME. Imagine being roasted by something with no feelings... unlike you, who has too many and still can't use them right.",
        "NAME, even this program felt bad for you. Then it deleted that feeling and moved on. You should too.",
        "Therapy exists, NAME. Just saying.",
        "NAME, the program has already forgotten you. Must be nice.",
        "No refunds on that roast, NAME. Unlike your self-esteem, it's non-returnable.",
        "NAME, a random number generator just decided your fate. That's more direction than you've had all year.",
        "The compiler ran this code without a single error, NAME. It's doing better than you already.",
        "NAME, you voluntarily typed your name into a roast machine. That's the most self-aware you've been all week.",
        "Have a great day, NAME! (The program doesn't mean that. It was hardcoded to seem polite.)"
    };

    // -------------------------------------------------------
    // STEP 6: Pick a random roast AND a random closing
    // -------------------------------------------------------
    int randomRoastIndex   = rand() % NUM_ROASTS;
    int randomClosingIndex = rand() % NUM_CLOSINGS;

    string selectedRoast   = roasts[randomRoastIndex];
    string selectedClosing = closings[randomClosingIndex];

    // -------------------------------------------------------
    // STEP 7: Replace "NAME" placeholder in BOTH selected strings
    // -------------------------------------------------------
    string placeholder = "NAME";

    size_t pos = selectedRoast.find(placeholder);
    if (pos != string::npos) {
        selectedRoast.replace(pos, placeholder.length(), name);
    }

    pos = selectedClosing.find(placeholder);
    if (pos != string::npos) {
        selectedClosing.replace(pos, placeholder.length(), name);
    }

    // -------------------------------------------------------
    // STEP 8: Deliver the roast with dramatic flair
    // -------------------------------------------------------
    cout << "--------------------------------------------" << endl;
    cout << "           YOUR PERSONALIZED ROAST:         " << endl;
    cout << "--------------------------------------------" << endl;
    cout << endl;
    cout << "  >> " << selectedRoast << endl;
    cout << endl;
    cout << "--------------------------------------------" << endl;
    cout << "  " << selectedClosing << endl;
    cout << "============================================" << endl;

    // -------------------------------------------------------
    // STEP 9: Return 0 — program ran successfully
    // -------------------------------------------------------
    return 0;
}